logging:
  level:
    root: info

vaadin:
  launch-browser: @vaadin.frontend.hotdeploy@
  allowed-packages: 
    - com.vaadin
    - org.vaadin
    - com
  productionMode: @vaadin.production.mode@
  frontend:
    hotdeploy: @vaadin.frontend.hotdeploy@


# Pour docker
# logging:
#   level:
#     root: info

# vaadin:
#   launch-browser: false
#   allowed-packages: 
#     - com.vaadin
#     - org.vaadin
#     - com
#   productionMode: true
#   frontend:
#     hotdeploy: false